import type { CommunityRecipe, Disruption, FoodItem, Recipe } from "./contracts";

export const foodItemsSeed: FoodItem[] = [
  {
    id: "1",
    name: { bm: "Ayam Standard", en: "Standard Chicken" },
    category: "protein",
    currentPrice: 10.4,
    previousPrice: 9.26,
    unit: "kg",
    region: "Selangor",
    trend: [8.9, 9.1, 9.26, 9.3, 9.5, 9.8, 10.1, 10.4],
    nationalAvg: 9.5,
  },
  {
    id: "2",
    name: { bm: "Beras Tempatan", en: "Local Rice" },
    category: "grain",
    currentPrice: 2.6,
    previousPrice: 2.55,
    unit: "kg",
    region: "Nasional",
    trend: [2.5, 2.52, 2.5, 2.55, 2.55, 2.58, 2.58, 2.6],
    nationalAvg: 2.55,
  },
  {
    id: "3",
    name: { bm: "Telur Gred A", en: "Grade A Eggs" },
    category: "protein",
    currentPrice: 0.45,
    previousPrice: 0.43,
    unit: "biji",
    region: "Nasional",
    trend: [0.4, 0.41, 0.42, 0.43, 0.43, 0.44, 0.44, 0.45],
    nationalAvg: 0.43,
  },
  {
    id: "4",
    name: { bm: "Minyak Masak", en: "Cooking Oil" },
    category: "oil",
    currentPrice: 4.2,
    previousPrice: 4.5,
    unit: "L",
    region: "Nasional",
    trend: [4.8, 4.7, 4.6, 4.5, 4.4, 4.35, 4.25, 4.2],
    nationalAvg: 4.4,
  },
  {
    id: "5",
    name: { bm: "Bawang Merah", en: "Shallots" },
    category: "vegetable",
    currentPrice: 7.8,
    previousPrice: 6.5,
    unit: "kg",
    region: "Perak",
    trend: [5.5, 5.8, 6, 6.2, 6.5, 7, 7.4, 7.8],
    nationalAvg: 6.2,
  },
  {
    id: "6",
    name: { bm: "Gula Pasir", en: "Granulated Sugar" },
    category: "staple",
    currentPrice: 2.85,
    previousPrice: 2.85,
    unit: "kg",
    region: "Nasional",
    trend: [2.85, 2.85, 2.85, 2.85, 2.85, 2.85, 2.85, 2.85],
    nationalAvg: 2.85,
  },
];

export const disruptionsSeed: Disruption[] = [
  {
    id: "d1",
    item: { bm: "Ayam Standard", en: "Standard Chicken" },
    region: "Selangor",
    severity: "high",
    description: {
      bm: "Harga purata naik ke RM10.40/kg akibat kelewatan bekalan dari ladang.",
      en: "Average price rose to RM10.40/kg due to farm supply delay.",
    },
    date: "2026-03-17",
  },
  {
    id: "d2",
    item: { bm: "Bawang Merah", en: "Shallots" },
    region: "Perak",
    severity: "medium",
    description: {
      bm: "Import dari India terganggu. Stok dijangka pulih dalam 2 minggu.",
      en: "India imports disrupted. Stock expected to recover in 2 weeks.",
    },
    date: "2026-03-16",
  },
  {
    id: "d3",
    item: { bm: "Sayur Sawi", en: "Mustard Greens" },
    region: "Cameron Highlands",
    severity: "low",
    description: {
      bm: "Hujan lebat menyebabkan penurunan sementara hasil tanaman.",
      en: "Heavy rain caused temporary drop in crop yield.",
    },
    date: "2026-03-15",
  },
];

export const commonIngredientsSeed = [
  // Grains & Carbs
  "Beras",
  "Kway Teow",
  "Mee",
  "Mie",
  "Nasi",
  "Roti",
  "Sagu",
  "Tepung",
  // Proteins
  "Ayam",
  "Daging",
  "Ikan",
  "Ikan Bilis",
  "Sosej",
  "Sotong",
  "Tahu",
  "Telur",
  "Tulang",
  "Tulang Daging",
  "Udang",
  "Udang Kering",
  "Wantan",
  // Vegetables & Fruits
  "Bawang Merah",
  "Bawang Putih",
  "Bengkoang",
  "Cincau",
  "Kentang",
  "Kulit Popiah",
  "Kulit Tahu",
  "Mangga",
  "Nanas",
  "Pisang",
  "Sayur Sawi",
  "Sawi",
  "Tauge",
  "Timun",
  "Tomato",
  "Ubi Kayu",
  // Herbs & Spices
  "Belacan",
  "Bunga Telang",
  "Daun Limau",
  "Daun Pandan",
  "Halia",
  "Kunyit",
  "Limau",
  "Limau nipis",
  "Serai",
  "Tempoyak",
  // Condiments & Sauces
  "Asam Jawa",
  "Cili",
  "Cuka",
  "Garam",
  "Gula",
  "Gula Merah",
  "Kicap",
  "Merah",
  "Milo",
  "Siram Bandung",
  // Condiments & Sauces (cont.)
  "Santan",
  // Dairy
  "Susu",
  // Fats & Oils
  "Kelapa",
  "Mentega",
  "Minyak Masak",
  // Nuts & Seeds
  "Kacang",
  "Kacang Merah",
  // Dessert / Sweeteners / Misc
  "Jeli",
  // Beverages
  "Teh",
  // Water / Ice
  "Ais",
  "Air",
  "Es Batu",
];

export const recipesSeed: Recipe[] = [
  // === SIMPLE RECIPES (2-3 ingredients) for testing 0/2, 1/2, 2/2 scenarios ===
  {
    id: "r001",
    name: { bm: "Nasi Putih", en: "Plain Steamed Rice" },
    ingredients: ["Beras", "Air"],
    prepTime: 5,
    estimatedCost: 0.5,
    calories: 200,
    tags: ["halal", "vegetarian", "cepat", "dasar"],
    steps: {
      bm: ["Bilas beras", "Masak dengan air", "Perah dan hidang"],
      en: ["Rinse rice", "Cook with water", "Drain and serve"],
    },
  },
  {
    id: "r002",
    name: { bm: "Telur Rebus", en: "Boiled Eggs" },
    ingredients: ["Telur", "Air", "Garam"],
    prepTime: 12,
    estimatedCost: 0.6,
    calories: 140,
    tags: ["halal", "vegetarian", "cepat", "sarapan"],
    steps: {
      bm: ["Masukkan telur dalam air mendidih", "Rebus 10 minit", "Kupas dan hidang"],
      en: ["Add eggs to boiling water", "Boil for 10 minutes", "Peel and serve"],
    },
  },
  {
    id: "r003",
    name: { bm: "Telur Goreng", en: "Fried Eggs" },
    ingredients: ["Telur", "Minyak Masak", "Garam"],
    prepTime: 7,
    estimatedCost: 0.5,
    calories: 180,
    tags: ["halal", "vegetarian", "cepat", "sarapan"],
    steps: {
      bm: ["Panaskan minyak", "Pecahkan telur", "Goreng sehingga masak"],
      en: ["Heat oil", "Crack eggs", "Fry until cooked"],
    },
  },
  {
    id: "r004",
    name: { bm: "Timun Carasel", en: "Cucumber Salad" },
    ingredients: ["Timun", "Garam", "Cili"],
    prepTime: 10,
    estimatedCost: 1.0,
    calories: 35,
    tags: ["halal", "vegetarian", "cepat", "segar"],
    steps: {
      bm: ["Kupas dan hiris timun", "Tabur garam", "Tambah cili jika suka"],
      en: ["Peel and slice cucumber", "Sprinkle salt", "Add chili if desired"],
    },
  },
  {
    id: "r005",
    name: { bm: "Telur Dadar Ringkas", en: "Simple Omelette" },
    ingredients: ["Telur", "Garam", "Minyak Masak"],
    prepTime: 10,
    estimatedCost: 0.6,
    calories: 200,
    tags: ["halal", "vegetarian", "cepat", "sarapan"],
    steps: {
      bm: ["Pukul telur dengan garam", "Goreng dalam minyak", "Lipat dan hidang"],
      en: ["Beat eggs with salt", "Fry in oil", "Fold and serve"],
    },
  },
  {
    id: "r006",
    name: { bm: "Air Gula Beras", en: "Sweet Rice Water" },
    ingredients: ["Beras", "Gula", "Air"],
    prepTime: 35,
    estimatedCost: 0.4,
    calories: 120,
    tags: ["halal", "vegetarian", "minuman", "tradisional"],
    steps: {
      bm: ["Rendam beras", "Masak sehingga pecah", "Tapis dan tambah gula"],
      en: ["Soak rice", "Cook until broken", "Strain and add sugar"],
    },
  },
  {
    id: "r007",
    name: { bm: "Sambal Bawang Ringkas", en: "Simple Onion Sambal" },
    ingredients: ["Bawang Merah", "Cili", "Minyak Masak"],
    prepTime: 25,
    estimatedCost: 1.5,
    calories: 85,
    tags: ["halal", "vegetarian", "pedas"],
    steps: {
      bm: ["Tumbuk bawang dan cili", "Panaskan minyak", "Tumis sehingga pecah"],
      en: ["Pound onion and chili", "Heat oil", "Stir-fry until broken"],
    },
  },
  // === MEDIUM RECIPES (4-5 ingredients) ===
  {
    id: "r008",
    name: { bm: "Nasi Goreng Telur", en: "Egg Fried Rice" },
    ingredients: ["Beras", "Telur", "Bawang Merah", "Kicap", "Minyak Masak", "Garam"],
    prepTime: 35,
    estimatedCost: 3.5,
    calories: 420,
    tags: ["halal", "cepat", "makan tengahari"],
    steps: {
      bm: ["Masak nasi terlebih dahulu", "Panaskan minyak dan tumis bawang", "Masukkan telur dan kicap", "Campurkan nasi dan kacau rata"],
      en: ["Cook rice first", "Heat oil and saute onion", "Add egg and soy sauce", "Mix in rice and stir well"],
    },
  },
  {
    id: "r009",
    name: { bm: "Telur Dadar Sayur", en: "Vegetable Omelette" },
    ingredients: ["Telur", "Bawang Merah", "Cili", "Garam", "Minyak Masak"],
    prepTime: 20,
    estimatedCost: 2.2,
    calories: 280,
    tags: ["halal", "vegetarian", "cepat"],
    steps: {
      bm: ["Pukul telur", "Campurkan bawang dan cili", "Goreng sehingga masak"],
      en: ["Beat eggs", "Mix in onion and chili", "Fry until cooked"],
    },
  },
  {
    id: "r010",
    name: { bm: "Sup Sayur Ringkas", en: "Simple Vegetable Soup" },
    ingredients: ["Sayur Sawi", "Bawang Putih", "Halia", "Garam", "Telur"],
    prepTime: 35,
    estimatedCost: 2.8,
    calories: 150,
    tags: ["halal", "vegetarian", "low-carb", "sup"],
    steps: {
      bm: ["Rebus air", "Masukkan bawang putih dan halia", "Tambah sayur sawi", "Pecahkan telur untuk sup"],
      en: ["Boil water", "Add garlic and ginger", "Add mustard greens", "Crack egg into soup"],
    },
  },
  {
    id: "r011",
    name: { bm: "Nasi Lemak Ringkas", en: "Simple Nasi Lemak" },
    ingredients: ["Beras", "Santan", "Telur", "Ikan Bilis", "Timun", "Garam"],
    prepTime: 60,
    estimatedCost: 4.5,
    calories: 550,
    tags: ["halal", "sarapan", "nasional"],
    steps: {
      bm: ["Masak nasi dengan santan", "Goreng ikan bilis", "Goreng telur", "Hidang dengan timun"],
      en: ["Cook rice with coconut milk", "Fry anchovies", "Fry egg", "Serve with cucumber"],
    },
  },
  {
    id: "r012",
    name: { bm: "Tumis Sawi Bawang Putih", en: "Garlic Stir-Fried Greens" },
    ingredients: ["Sayur Sawi", "Bawang Putih", "Minyak Masak", "Garam"],
    prepTime: 15,
    estimatedCost: 2,
    calories: 90,
    tags: ["halal", "vegetarian", "low-carb", "cepat"],
    steps: {
      bm: ["Panaskan minyak", "Tumis bawang putih", "Masukkan sawi", "Masak 3 minit"],
      en: ["Heat oil", "Saute garlic", "Add greens", "Cook 3 minutes"],
    },
  },
  {
    id: "r013",
    name: { bm: "Sambal Telur", en: "Egg Sambal" },
    ingredients: ["Telur", "Cili", "Bawang Merah", "Kicap", "Minyak Masak", "Gula"],
    prepTime: 35,
    estimatedCost: 3.0,
    calories: 320,
    tags: ["halal", "pedas", "lauk"],
    steps: {
      bm: ["Goreng telur dan ketepikan", "Tumis cili dan bawang", "Masukkan kicap dan gula", "Masukkan telur dan kacau"],
      en: ["Fry eggs and set aside", "Stir-fry chili and onion", "Add soy sauce and sugar", "Add eggs and mix"],
    },
  },
  {
    id: "r014",
    name: { bm: "Ayam Goreng Ringkas", en: "Simple Fried Chicken" },
    ingredients: ["Ayam", "Kunyit", "Garam", "Bawang Putih", "Minyak Masak"],
    prepTime: 45,
    estimatedCost: 8.0,
    calories: 380,
    tags: ["halal", "lauk", "ayam"],
    steps: {
      bm: ["Potong ayam dan perap dengan rempah", "Panaskan minyak", "Goreng sehingga keemasan", "Tiriskan"],
      en: ["Cut chicken and marinate with spices", "Heat oil", "Fry until golden", "Drain"],
    },
  },
  {
    id: "r015",
    name: { bm: "Tomato Telur Masak Merah", en: "Tomato Egg in Red Sauce" },
    ingredients: ["Telur", "Tomato", "Bawang Putih", "Kicap", "Minyak Masak", "Gula"],
    prepTime: 30,
    estimatedCost: 3.5,
    calories: 290,
    tags: ["halal", "cepat", "lauk"],
    steps: {
      bm: ["Goreng telur dan ketepikan", "Tumis bawang putih", "Masukkan tomato dan kicap", "Masukkan telur dan masak"],
      en: ["Fry eggs and set aside", "Saute garlic", "Add tomato and soy sauce", "Add eggs and cook"],
    },
  },
  // === AUTHENTIC MALAYSIAN MAIN COURSES ===
  {
    id: "r016",
    name: { bm: "Nasi Lemak Sambal Ikan Bilis", en: "Nasi Lemak with Anchovy Sambal" },
    ingredients: ["Beras", "Santan", "Ikan Bilis", "Cili", "Bawang Merah", "Bawang Putih", "Halia", "Gula", "Timun", "Telur", "Kicap", "Minyak Masak", "Garam"],
    prepTime: 85,
    estimatedCost: 8.0,
    calories: 620,
    tags: ["halal", "nasional", "sarapan", "iconik"],
    steps: {
      bm: ["Masak beras dengan santan dan daun pandan", "Kisar cili, bawang merah, bawang putih, halia", "Tumis rempah sehingga pecah minyak", "Masukkan ikan bilis dan masak", "Goreng telur", "Susun nasi dengan semua hiasan"],
      en: ["Cook rice with coconut milk and pandan leaves", "Blend chili, shallots, garlic, ginger", "Fry spice paste until oil separates", "Add anchovies and cook", "Fry eggs", "Arrange rice with all garnishes"],
    },
  },
  {
    id: "r017",
    name: { bm: "Rendang Daging", en: "Beef Rendang" },
    ingredients: ["Daging", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Kicap", "Gula", "Minyak Masak", "Daun Limau"],
    prepTime: 180,
    estimatedCost: 25.0,
    calories: 520,
    tags: ["halal", "lauk", "rendang", "hari Raya"],
    steps: {
      bm: ["Kisar rempah dan tumis sehingga pecah minyak", "Masukkan daging dan masak sehingga gris keluar", "Tambah santan dan rempah", "Masak dengan api kecil selama 2 jam", "Kacau sehingga pekat"],
      en: ["Blend spices and fry until oil separates", "Add beef and cook until fat renders", "Add coconut milk and spices", "Simmer on low heat for 2 hours", "Stir until thick"],
    },
  },
  {
    id: "r018",
    name: { bm: "Ayam Rendang", en: "Chicken Rendang" },
    ingredients: ["Ayam", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Kicap", "Minyak Masak", "Daun Limau"],
    prepTime: 135,
    estimatedCost: 15.0,
    calories: 450,
    tags: ["halal", "lauk", "rendang", "ayam"],
    steps: {
      bm: ["Kisar rempah dan tumis dengan minyak", "Masukkan ayam dan masak sehingga gris keluar", "Tambah santan dan daun limau", "Masak dengan api kecil sehingga pekat"],
      en: ["Blend spices and fry with oil", "Add chicken and cook until fat renders", "Add coconut milk and lime leaves", "Simmer until thick"],
    },
  },
  {
    id: "r019",
    name: { bm: "Satay Ayam", en: "Chicken Satay" },
    ingredients: ["Ayam", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kicap", "Gula", "Minyak Masak", "Kacang", "Cili"],
    prepTime: 90,
    estimatedCost: 18.0,
    calories: 380,
    tags: ["halal", "barbeque", "party", "iconik"],
    steps: {
      bm: ["Potong ayam dan perap dengan rempah", "Tusuk ayam pada lidi satay", "Grill atau panggang sehingga masak", "Hidang dengan sos kacang"],
      en: ["Cut chicken and marinate with spices", "Thread chicken onto satay sticks", "Grill until cooked", "Serve with peanut sauce"],
    },
  },
  {
    id: "r020",
    name: { bm: "Laksa Lemak", en: "Coconut Laksa" },
    ingredients: ["Mie", "Santan", "Udang Kering", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Telur", "Timun", "Tauge", "Minyak Masak", "Garam"],
    prepTime: 85,
    estimatedCost: 12.0,
    calories: 480,
    tags: ["halal", "sup", "mie", "nasional"],
    steps: {
      bm: ["Kisar rempah dan tumis", "Masak dengan santan sehingga mendidih", "Rebus mie dan letakkan dalam mangkuk", "Tuang kuah dan hias dengan telur, timun, tauge"],
      en: ["Blend spices and fry", "Cook with coconut milk until boiling", "Boil noodles and place in bowl", "Pour soup and garnish with egg, cucumber, bean sprouts"],
    },
  },
  {
    id: "r021",
    name: { bm: "Asam Laksa", en: "Sour Laksa" },
    ingredients: ["Mie", "Ikan", "Asam Jawa", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Cili", "Timun", "Nanas", "Minyak Masak", "Gula", "Garam"],
    prepTime: 95,
    estimatedCost: 14.0,
    calories: 420,
    tags: ["halal", "sup", "mie", "Pedagang", "masam"],
    steps: {
      bm: ["Rebus ikan untuk kuah", "Kisar rempah dan masak dengan air ikan", "Tambah asam jawa dan gula", "Hias dengan mie, timun, nanas dan herba"],
      en: ["Boil fish for broth", "Blend spices and cook with fish water", "Add tamarind and sugar", "Garnish with noodles, cucumber, pineapple and herbs"],
    },
  },
  {
    id: "r022",
    name: { bm: "Mee Goreng Mamak", en: "Mamak Fried Noodles" },
    ingredients: ["Mie", "Ayam", "Telur", "Bawang Merah", "Bawang Putih", "Kicap", "Tomato", "Sawi", "Minyak Masak", "Cili", "Gula"],
    prepTime: 45,
    estimatedCost: 8.0,
    calories: 520,
    tags: ["halal", "cepat", "mie", "mamak"],
    steps: {
      bm: ["Goreng ayam dan telur berasingan", "Tumis bawang dan cili", "Masukkan mie dan kicap", "Campurkan semua bahan dan kacau rata"],
      en: ["Fry chicken and eggs separately", "Saute onion and chili", "Add noodles and soy sauce", "Combine all ingredients and stir well"],
    },
  },
  {
    id: "r023",
    name: { bm: "Char Kway Teow", en: "Stir-Fried Flat Noodles" },
    ingredients: ["Kway Teow", "Udang", "Telur", "Ikan Bilis", "Bawang Putih", "Kicap", "Minyak Masak", "Tauge", "Sosej"],
    prepTime: 35,
    estimatedCost: 10.0,
    calories: 580,
    tags: ["halal", "cepat", "mie", "hawker"],
    steps: {
      bm: ["Panaskan wok dengan minyak yang banyak", "Goreng telur dan ketepikan", "Tumis bawang dan udang", "Masukkan kway teow dan kicap", "Akhir sekali masukkan tauge"],
      en: ["Heat wok with plenty of oil", "Fry egg and set aside", "Saute garlic and shrimp", "Add kway teow and soy sauce", "Finally add bean sprouts"],
    },
  },
  {
    id: "r024",
    name: { bm: "Nasi Goreng Kampung", en: "Village Fried Rice" },
    ingredients: ["Beras", "Telur", "Bawang Merah", "Bawang Putih", "Cili", "Kicap", "Ikan Bilis", "Minyak Masak", "Garam", "Halia"],
    prepTime: 40,
    estimatedCost: 4.0,
    calories: 450,
    tags: ["halal", "cepat", "nasi", "kampung"],
    steps: {
      bm: ["Masak nasi terlebih dahulu", "Tumis bawang, bawang putih, halia", "Masukkan cili dan kicap", "Masukkan nasi dan ikan bilis", "Akhir sekali masukkan telur"],
      en: ["Cook rice first", "Saute onion, garlic, ginger", "Add chili and soy sauce", "Add rice and anchovies", "Finally add egg"],
    },
  },
  {
    id: "r025",
    name: { bm: "Nasi Goreng Pattaya", en: "Pattaya Fried Rice" },
    ingredients: ["Beras", "Telur", "Ayam", "Bawang Merah", "Bawang Putih", "Kicap", "Minyak Masak", "Timun", "Tomato"],
    prepTime: 55,
    estimatedCost: 8.0,
    calories: 550,
    tags: ["halal", "lauk", "nasi", "popular"],
    steps: {
      bm: ["Masak nasi goreng biasa", "Goreng telur menjadi telur hampa", "Isikan nasi goreng ke dalam telur hampa", "Hias dengan timun dan tomato"],
      en: ["Make regular fried rice", "Fry egg to make omelette", "Fill omelette with fried rice", "Garnish with cucumber and tomato"],
    },
  },
  {
    id: "r026",
    name: { bm: "Hainanese Chicken Rice", en: "Hainanese Chicken Rice" },
    ingredients: ["Ayam", "Beras", "Bawang Putih", "Halia", "Timun", "Tomato", "Kicap", "Minyak Masak", "Garam"],
    prepTime: 100,
    estimatedCost: 15.0,
    calories: 480,
    tags: ["halal", "nasi", "chicken", "Singaporean"],
    steps: {
      bm: ["Rebus ayam untuk mendapatkan kuah", "Masak beras dengan kuah ayam", "Sejukkan ayam dan potong", "Hidas dengan nasi, ayam, timun dan kicap halia"],
      en: ["Boil chicken to get broth", "Cook rice with chicken broth", "Cool chicken and cut", "Serve with rice, chicken, cucumber and ginger sauce"],
    },
  },
  {
    id: "r027",
    name: { bm: "Nasi Kandar", en: "Nasi Kandar" },
    ingredients: ["Beras", "Ayam", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Kicap", "Minyak Masak", "Timun"],
    prepTime: 100,
    estimatedCost: 12.0,
    calories: 580,
    tags: ["halal", "nasi", "Penang", "berat"],
    steps: {
      bm: ["Masak ayam kari dengan rempah", "Masak nasi dengan santan", "Susun nasi dengan ayam kari dan telur"],
      en: ["Cook curry chicken with spices", "Cook rice with coconut milk", "Arrange rice with curry chicken and egg"],
    },
  },
  {
    id: "r028",
    name: { bm: "Mee Rebus", en: "Mee Rebus" },
    ingredients: ["Mie", "Kentang", "Telur", "Tauge", "Bawang Merah", "Bawang Putih", "Halia", "Kicap", "Santan", "Minyak Masak", "Gula", "Garam"],
    prepTime: 70,
    estimatedCost: 7.0,
    calories: 450,
    tags: ["halal", "mie", "kuah", "popular"],
    steps: {
      bm: ["Masak kentang sehingga lembut", "Kisar bawang dan halia", "Masak dengan kicap dan gula", "Letakkan mie dan tauge dalam mangkuk", "Tuang kuah di atas"],
      en: ["Cook potatoes until soft", "Blend onion and ginger", "Cook with soy sauce and sugar", "Place noodles and bean sprouts in bowl", "Pour sauce over"],
    },
  },
  {
    id: "r029",
    name: { bm: "Ayam Masak Merah", en: "Red Cooked Chicken" },
    ingredients: ["Ayam", "Tomato", "Cili", "Bawang Merah", "Bawang Putih", "Kicap", "Gula", "Minyak Masak", "Garam"],
    prepTime: 75,
    estimatedCost: 12.0,
    calories: 400,
    tags: ["halal", "lauk", "ayam", "merah"],
    steps: {
      bm: ["Goreng ayam sehingga perang", "Kisar tomato dan cili", "Tumis sehingga pecah minyak", "Masukkan ayam dan masak perlahan"],
      en: ["Fry chicken until brown", "Blend tomato and chili", "Stir-fry until oil separates", "Add chicken and cook slowly"],
    },
  },
  {
    id: "r030",
    name: { bm: "Sambal Udang", en: "Sambal Prawns" },
    ingredients: ["Udang", "Cili", "Bawang Merah", "Bawang Putih", "Tomato", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 40,
    estimatedCost: 15.0,
    calories: 280,
    tags: ["halal", "lauk", "udang", "pedas"],
    steps: {
      bm: ["Kisar cili dan bawang", "Tumis sehingga pecah minyak", "Masukkan udang dan tomato", "Masak sehingga udang masak"],
      en: ["Blend chili and onion", "Stir-fry until oil separates", "Add prawns and tomato", "Cook until prawns are done"],
    },
  },
  {
    id: "r031",
    name: { bm: "Sambal Sotong", en: "Sambal Squid" },
    ingredients: ["Sotong", "Cili", "Bawang Merah", "Bawang Putih", "Tomato", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 45,
    estimatedCost: 14.0,
    calories: 260,
    tags: ["halal", "lauk", "sotong", "pedas"],
    steps: {
      bm: ["Bersihkan sotong dan potong", "Kisar cili dan bawang", "Tumis rempah", "Masukkan sotong dan masak"],
      en: ["Clean and cut squid", "Blend chili and onion", "Fry spices", "Add squid and cook"],
    },
  },
  {
    id: "r032",
    name: { bm: "Ikan Goreng Sambal", en: "Fried Fish with Sambal" },
    ingredients: ["Ikan", "Cili", "Bawang Merah", "Bawang Putih", "Tomato", "Kicap", "Minyak Masak", "Gula", "Garam", "Kunyit"],
    prepTime: 45,
    estimatedCost: 12.0,
    calories: 320,
    tags: ["halal", "lauk", "ikan", "pedas"],
    steps: {
      bm: ["Perap ikan dengan kunyit dan garam", "Goreng ikan sehingga garing", "Kisar rempah dan tumis", "Masukkan tomato dan gula", "Tuang sambal di atas ikan"],
      en: ["Marinate fish with turmeric and salt", "Fry fish until crispy", "Blend spices and stir-fry", "Add tomato and sugar", "Pour sambal over fish"],
    },
  },
  {
    id: "r033",
    name: { bm: "Asam Pedas Ikan", en: "Sour Spicy Fish Stew" },
    ingredients: ["Ikan", "Asam Jawa", "Cili", "Bawang Merah", "Bawang Putih", "Serai", "Tomato", "Nanas", "Minyak Masak", "Gula", "Garam"],
    prepTime: 60,
    estimatedCost: 13.0,
    calories: 290,
    tags: ["halal", "lauk", "ikan", "masam", "Pedagang"],
    steps: {
      bm: ["Masak air dengan asam jawa", "Masukkan rempah yang dikisar", "Tambah tomato dan nanas", "Masukkan ikan dan masak"],
      en: ["Boil water with tamarind", "Add blended spices", "Add tomato and pineapple", "Add fish and cook"],
    },
  },
  {
    id: "r034",
    name: { bm: "Gulai Daging", en: "Beef Curry" },
    ingredients: ["Daging", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Kicap", "Minyak Masak", "Daun Limau"],
    prepTime: 130,
    estimatedCost: 22.0,
    calories: 480,
    tags: ["halal", "lauk", "daging", "gulai"],
    steps: {
      bm: ["Kisar rempah dan tumis", "Masukkan daging dan masak", "Tambah santan dan daun limau", "Masak sehingga daging lembut"],
      en: ["Blend spices and fry", "Add beef and cook", "Add coconut milk and lime leaves", "Cook until beef is tender"],
    },
  },
  {
    id: "r035",
    name: { bm: "Gulai Ayam", en: "Chicken Curry" },
    ingredients: ["Ayam", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Minyak Masak", "Daun Limau"],
    prepTime: 95,
    estimatedCost: 14.0,
    calories: 420,
    tags: ["halal", "lauk", "ayam", "gulai"],
    steps: {
      bm: ["Kisar rempah dan tumis dengan minyak", "Masukkan ayam dan masak", "Tambah santan", "Masak sehingga ayam masak"],
      en: ["Blend spices and fry with oil", "Add chicken and cook", "Add coconut milk", "Cook until chicken is done"],
    },
  },
  {
    id: "r036",
    name: { bm: "Soto Ayam", en: "Chicken Soto" },
    ingredients: ["Ayam", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Mie", "Tauge", "Telur", "Timun", "Minyak Masak", "Garam"],
    prepTime: 90,
    estimatedCost: 12.0,
    calories: 380,
    tags: ["halal", "sup", "ayam", "popular"],
    steps: {
      bm: ["Rebus ayam untuk kuah", "Kisar rempah dan tumis", "Masukkan ke dalam kuah", "Hias dengan mie, tauge, telur dan timun"],
      en: ["Boil chicken for broth", "Blend spices and fry", "Add to broth", "Garnish with noodles, bean sprouts, egg and cucumber"],
    },
  },
  {
    id: "r037",
    name: { bm: "Bak Kut Teh", en: "Pork Ribs Herbal Soup" },
    ingredients: ["Tulang Daging", "Bawang Putih", "Halia", "Kicap", "Timun", "Minyak Masak", "Garam"],
    prepTime: 140,
    estimatedCost: 18.0,
    calories: 350,
    tags: ["tidak halal", "sup", "daging", "herba"],
    steps: {
      bm: ["Rebus tulang dengan bawang putih dan halia", "Masak selama 2 jam", "Perasa dengan kicap dan garam", "Hias dengan timun"],
      en: ["Boil ribs with garlic and ginger", "Cook for 2 hours", "Season with soy sauce and salt", "Garnish with cucumber"],
    },
  },
  {
    id: "r038",
    name: { bm: "Kari Kapitan", en: "Curry Kapitan" },
    ingredients: ["Ayam", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Kicap", "Minyak Masak", "Kentang"],
    prepTime: 105,
    estimatedCost: 13.0,
    calories: 440,
    tags: ["halal", "lauk", "ayam", "Nyonya"],
    steps: {
      bm: ["Kisar rempah Nyonya", "Tumis dengan minyak sehingga pecah minyak", "Masukkan ayam dan kentang", "Tambah santan dan masak"],
      en: ["Blend Nyonya spices", "Fry with oil until oil separates", "Add chicken and potatoes", "Add coconut milk and cook"],
    },
  },
  {
    id: "r039",
    name: { bm: "Ayam Pongteh", en: "Nyonya Chicken Stew" },
    ingredients: ["Ayam", "Kentang", "Bawang Merah", "Bawang Putih", "Kicap", "Gula", "Minyak Masak", "Garam"],
    prepTime: 75,
    estimatedCost: 11.0,
    calories: 390,
    tags: ["halal", "lauk", "ayam", "Nyonya"],
    steps: {
      bm: ["Tumis bawang sehingga wangi", "Masukkan ayam dan kicap", "Tambah kentang dan air", "Masak sehingga pekat"],
      en: ["Saute onion until fragrant", "Add chicken and soy sauce", "Add potatoes and water", "Cook until thick"],
    },
  },
  {
    id: "r040",
    name: { bm: "Chap Chye", en: "Nyonya Mixed Vegetable Stew" },
    ingredients: ["Sayur Sawi", "Timun", "Tomato", "Bawang Merah", "Bawang Putih", "Kicap", "Santan", "Minyak Masak", "Gula", "Garam"],
    prepTime: 70,
    estimatedCost: 8.0,
    calories: 220,
    tags: ["halal", "vegetarian", "lauk", "Nyonya"],
    steps: {
      bm: ["Tumis bawang dan rempah", "Masukkan sayur dan santan", "Masak sehingga lembut"],
      en: ["Saute onion and spices", "Add vegetables and coconut milk", "Cook until tender"],
    },
  },
  // === NOODLE DISHES ===
  {
    id: "r041",
    name: { bm: "Mee Siam", en: "Mee Siam" },
    ingredients: ["Mie", "Telur", "Tauge", "Bawang Merah", "Bawang Putih", "Kicap", "Asam Jawa", "Minyak Masak", "Gula", "Garam"],
    prepTime: 55,
    estimatedCost: 7.0,
    calories: 420,
    tags: ["halal", "mie", "Nyonya", "masam"],
    steps: {
      bm: ["Kisar rempah dan masak kuah", "Goreng mie dan telur", "Hias dengan tauge"],
      en: ["Blend spices and cook sauce", "Fry noodles and egg", "Garnish with bean sprouts"],
    },
  },
  {
    id: "r042",
    name: { bm: "Wantan Mee", en: "Wanton Noodles" },
    ingredients: ["Mie", "Wantan", "Bawang Putih", "Kicap", "Minyak Masak", "Sayur Sawi", "Garam"],
    prepTime: 60,
    estimatedCost: 8.0,
    calories: 450,
    tags: ["halal", "mie", "cina", "popular"],
    steps: {
      bm: ["Rebus wantan sehingga naik", "Masak mie dan sayur", "Gaul dengan kicap dan minyak bawang"],
      en: ["Boil wantan until floating", "Cook noodles and vegetables", "Mix with soy sauce and garlic oil"],
    },
  },
  {
    id: "r043",
    name: { bm: "Hokkien Mee", en: "Hokkien Noodles" },
    ingredients: ["Mie", "Udang", "Telur", "Bawang Putih", "Kicap", "Santan", "Minyak Masak", "Tauge"],
    prepTime: 55,
    estimatedCost: 10.0,
    calories: 480,
    tags: ["halal", "mie", "cina", "hawker"],
    steps: {
      bm: ["Goreng udang dan telur", "Tumis bawang putih", "Masukkan mie dan kicap", "Tambah santan dan tauge"],
      en: ["Fry shrimp and egg", "Saute garlic", "Add noodles and soy sauce", "Add coconut milk and bean sprouts"],
    },
  },
  {
    id: "r044",
    name: { bm: "Laksa Johor", en: "Johor Laksa" },
    ingredients: ["Beras", "Ikan", "Santan", "Serai", "Halia", "Bawang Merah", "Bawang Putih", "Kunyit", "Cili", "Timun", "Minyak Masak"],
    prepTime: 120,
    estimatedCost: 15.0,
    calories: 460,
    tags: ["halal", "nasi", "laksa", "Johor"],
    steps: {
      bm: ["Buat noodle dari beras", "Masak kuah dengan ikan dan santan", "Hias dengan timun dan telur"],
      en: ["Make noodles from rice", "Cook gravy with fish and coconut milk", "Garnish with cucumber and egg"],
    },
  },
  // === RICE DISHES ===
  {
    id: "r045",
    name: { bm: "Nasi Kerabu", en: "Blue Rice Salad" },
    ingredients: ["Beras", "Bunga Telang", "Santan", "Serai", "Halia", "Timun", "Tomato", "Bawang Merah", "Minyak Masak", "Garam"],
    prepTime: 70,
    estimatedCost: 9.0,
    calories: 380,
    tags: ["halal", "nasi", "Kelantan", "segar"],
    steps: {
      bm: ["Rendam beras dengan bunga telang", "Masak nasi dengan santan", "Sediakan ulam dan sambal"],
      en: ["Soak rice with butterfly pea flowers", "Cook rice with coconut milk", "Prepare herbs and sambal"],
    },
  },
  {
    id: "r046",
    name: { bm: "Nasi Ulam", en: "Herbed Rice" },
    ingredients: ["Beras", "Bawang Merah", "Serai", "Minyak Masak", "Timun", "Ikan Bilis", "Udang Kering", "Cili", "Gula", "Garam"],
    prepTime: 75,
    estimatedCost: 8.0,
    calories: 360,
    tags: ["halal", "nasi", "Penang", "ulam"],
    steps: {
      bm: ["Masak nasi dan sejukkan", "Kisar ikan bilis dan udang kering", "Campurkan semua bahan dan kacau rata"],
      en: ["Cook rice and cool", "Blend anchovies and dried shrimp", "Combine all ingredients and mix well"],
    },
  },
  {
    id: "r047",
    name: { bm: "Nasi Dagang", en: "Trader's Rice" },
    ingredients: ["Beras", "Santan", "Serai", "Halia", "Kunyit", "Ikan", "Cili", "Bawang Merah", "Minyak Masak", "Garam"],
    prepTime: 90,
    estimatedCost: 12.0,
    calories: 480,
    tags: ["halal", "nasi", "Terengganu", "sarapan"],
    steps: {
      bm: ["Masak beras dengan santan dan rempah", "Masak ikan dengan kuah kari", "Hidang bersama"],
      en: ["Cook rice with coconut milk and spices", "Cook fish with curry sauce", "Serve together"],
    },
  },
  {
    id: "r048",
    name: { bm: "Nasi Minyak", en: "Ghee Rice" },
    ingredients: ["Beras", "Minyak Masak", "Bawang Merah", "Serai", "Halia", "Kicap", "Garam"],
    prepTime: 45,
    estimatedCost: 5.0,
    calories: 420,
    tags: ["halal", "nasi", "cepat", "beraroma"],
    steps: {
      bm: ["Tumis bawang, serai dan halia", "Masak beras dengan air", "Gaul minyak tumisan dengan nasi"],
      en: ["Saute onion, lemongrass and ginger", "Cook rice with water", "Mix fried oil with rice"],
    },
  },
  // === VEGETABLE DISHES ===
  {
    id: "r049",
    name: { bm: "Sambal Kangkung", en: "Sambal Water Spinach" },
    ingredients: ["Sayur Sawi", "Cili", "Bawang Merah", "Bawang Putih", "Kicap", "Minyak Masak", "Gula", "Garam", "Udang Kering"],
    prepTime: 30,
    estimatedCost: 4.0,
    calories: 150,
    tags: ["halal", "vegetarian", "sayur", "pedas"],
    steps: {
      bm: ["Blans kangkung", "Kisar rempah dan udang kering", "Tumis sehingga pecah minyak", "Masukkan kangkung"],
      en: ["Blanch water spinach", "Blend spices and dried shrimp", "Fry until oil separates", "Add water spinach"],
    },
  },
  {
    id: "r050",
    name: { bm: "Kangkung Belacan", en: "Water Spinach with Shrimp Paste" },
    ingredients: ["Sayur Sawi", "Cili", "Udang Kering", "Bawang Putih", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 27,
    estimatedCost: 3.5,
    calories: 130,
    tags: ["halal", "vegetarian", "sayur", "pedas"],
    steps: {
      bm: ["Blans kangkung", "Tumis cili dan udang kering", "Masukkan kangkung dan kicap"],
      en: ["Blanch water spinach", "Stir-fry chili and dried shrimp", "Add water spinach and soy sauce"],
    },
  },
  {
    id: "r051",
    name: { bm: "Tumis Timun Cili", en: "Stir-Fried Cucumber with Chili" },
    ingredients: ["Timun", "Cili", "Bawang Putih", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 20,
    estimatedCost: 2.5,
    calories: 90,
    tags: ["halal", "vegetarian", "sayur", "cepat"],
    steps: {
      bm: ["Potong timun", "Tumis bawang putih dan cili", "Masukkan timun dan perasa"],
      en: ["Cut cucumber", "Saute garlic and chili", "Add cucumber and season"],
    },
  },
  {
    id: "r052",
    name: { bm: "Sayur Lodeh", en: "Vegetable Curry" },
    ingredients: ["Timun", "Tomato", "Sayur Sawi", "Santan", "Bawang Merah", "Bawang Putih", "Cili", "Minyak Masak", "Gula", "Garam"],
    prepTime: 50,
    estimatedCost: 6.0,
    calories: 180,
    tags: ["halal", "vegetarian", "sayur", "lemak"],
    steps: {
      bm: ["Tumis rempah", "Masukkan sayur dan santan", "Masak perlahan"],
      en: ["Fry spices", "Add vegetables and coconut milk", "Cook slowly"],
    },
  },
  // === SNACKS ===
  {
    id: "r053",
    name: { bm: "Roti Canai", en: "Roti Canai" },
    ingredients: ["Tepung", "Telur", "Minyak Masak", "Gula", "Garam", "Santan"],
    prepTime: 80,
    estimatedCost: 3.0,
    calories: 280,
    tags: ["halal", "sarapan", "snack", "mamak"],
    steps: {
      bm: ["Gaul doh dan rehatkan", "Renggangkan doh berulang kali", "Goreng dengan minyak"],
      en: ["Mix dough and rest", "Stretch dough repeatedly", "Fry with oil"],
    },
  },
  {
    id: "r054",
    name: { bm: "Murtabak", en: "Murtabak" },
    ingredients: ["Tepung", "Telur", "Ayam", "Bawang Merah", "Cili", "Minyak Masak", "Kicap", "Gula", "Garam"],
    prepTime: 70,
    estimatedCost: 6.0,
    calories: 350,
    tags: ["halal", "sarapan", "mamak", "isian"],
    steps: {
      bm: ["Gaul doh dan canai", "Isi dengan ayam dan rempah", "Lipat dan goreng"],
      en: ["Make dough and roll", "Fill with chicken and spices", "Fold and fry"],
    },
  },
  {
    id: "r055",
    name: { bm: "Popiah", en: "Fresh Spring Rolls" },
    ingredients: ["Kulit Popiah", "Timun", "Telur", "Tauge", "Bawang Merah", "Bawang Putih", "Kicap", "Gula", "Garam"],
    prepTime: 45,
    estimatedCost: 5.0,
    calories: 220,
    tags: ["halal", "snack", "Nyonya", "segar"],
    steps: {
      bm: ["Sediakan filling", "Letakkan filling pada kulit", "Gulung dan potong"],
      en: ["Prepare filling", "Place filling on skin", "Roll and cut"],
    },
  },
  {
    id: "r056",
    name: { bm: "Lor Bak", en: "Fried Prawn Rolls" },
    ingredients: ["Kulit Tahu", "Daging", "Bawang Merah", "Bawang Putih", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 60,
    estimatedCost: 7.0,
    calories: 300,
    tags: ["halal", "snack", "cina", "goreng"],
    steps: {
      bm: ["Kisar daging dan rempah", "Bungkus dengan kulit tahu", "Goreng sehingga keemasan"],
      en: ["Blend meat and spices", "Wrap with tofu skin", "Fry until golden"],
    },
  },
  {
    id: "r057",
    name: { bm: "Otak-Otak", en: "Grilled Fish Custard" },
    ingredients: ["Ikan", "Telur", "Santan", "Cili", "Bawang Merah", "Bawang Putih", "Serai", "Minyak Masak", "Gula", "Garam"],
    prepTime: 50,
    estimatedCost: 8.0,
    calories: 180,
    tags: ["halal", "snack", "Nyonya", "panggang"],
    steps: {
      bm: ["Kisar ikan dan rempah", "Campurkan dengan telur dan santan", "Bungkus dengan daun pisang", "Panggang"],
      en: ["Blend fish and spices", "Mix with egg and coconut milk", "Wrap in banana leaves", "Grill"],
    },
  },
  {
    id: "r058",
    name: { bm: "Kuih Pie Tee", en: "Top Hats" },
    ingredients: ["Tepung", "Timun", "Bawang Merah", "Udang Kering", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 70,
    estimatedCost: 6.0,
    calories: 200,
    tags: ["halal", "snack", "Nyonya", "keri"],
    steps: {
      bm: ["Buat kulit kuih pie tee", "Sediakan filling", "Isi danhidang"],
      en: ["Make pie tee shells", "Prepare filling", "Fill and serve"],
    },
  },
  {
    id: "r059",
    name: { bm: "Satay Celup", en: "Dipping Satay" },
    ingredients: ["Tahu", "Santan", "Kicap", "Gula", "Cili", "Minyak Masak", "Garam"],
    prepTime: 25,
    estimatedCost: 4.0,
    calories: 160,
    tags: ["halal", "snack", "cepat", "vegetarian"],
    steps: {
      bm: ["Potong tahu dan goreng", "Masak kuah satay", "Celup dan makan"],
      en: ["Cut and fry tofu", "Cook satay sauce", "Dip and eat"],
    },
  },
  // === DESSERTS / KUIH ===
  {
    id: "r060",
    name: { bm: "Ondeh-Ondeh", en: "Glutinous Rice Balls" },
    ingredients: ["Tepung", "Gula", "Kelapa", "Santan", "Garam"],
    prepTime: 75,
    estimatedCost: 5.0,
    calories: 280,
    tags: ["halal", "kuih", "tradisional", "manis"],
    steps: {
      bm: ["Buat doh dan bulatkan", "Isi dengan gula melaka", "Rebus dan gulungkan kelapa"],
      en: ["Make dough and shape", "Fill with palm sugar", "Boil and roll in coconut"],
    },
  },
  {
    id: "r061",
    name: { bm: "Kuih Lapis", en: "Layered Cake" },
    ingredients: ["Tepung", "Santan", "Gula", "Garam", "Minyak Masak"],
    prepTime: 150,
    estimatedCost: 8.0,
    calories: 320,
    tags: ["halal", "kuih", "tradisional", "Steamed"],
    steps: {
      bm: ["Buat batter", "Kukus lapisan demi lapisan", "Sejukkan dan potong"],
      en: ["Make batter", "Steam layer by layer", "Cool and cut"],
    },
  },
  {
    id: "r062",
    name: { bm: "Seri Muka", en: "Coconut Custard Kuih" },
    ingredients: ["Beras", "Santan", "Telur", "Gula", "Daun Pandan", "Minyak Masak", "Garam"],
    prepTime: 125,
    estimatedCost: 7.0,
    calories: 300,
    tags: ["halal", "kuih", "tradisional", "Steamed"],
    steps: {
      bm: ["Masak pulut dengan santan", "Buat custard dari telur dan gula", "Kukus sehingga masak"],
      en: ["Cook glutinous rice with coconut milk", "Make custard from egg and sugar", "Steam until cooked"],
    },
  },
  {
    id: "r063",
    name: { bm: "Apam Balik", en: "Apam Balik" },
    ingredients: ["Tepung", "Telur", "Santan", "Gula", "Kacang", "Minyak Masak", "Garam"],
    prepTime: 50,
    estimatedCost: 4.0,
    calories: 260,
    tags: ["halal", "kuih", "sarapan", "goreng"],
    steps: {
      bm: ["Buat batter", "Tuangkan dalam acuan", "Tambah filling dan lipat"],
      en: ["Make batter", "Pour into mold", "Add filling and fold"],
    },
  },
  {
    id: "r064",
    name: { bm: "Kuih Dadar", en: "Pandan Crepes" },
    ingredients: ["Tepung", "Telur", "Santan", "Gula", "Kelapa", "Daun Pandan", "Minyak Masak", "Garam"],
    prepTime: 60,
    estimatedCost: 5.0,
    calories: 240,
    tags: ["halal", "kuih", "Nyonya", "segar"],
    steps: {
      bm: ["Buat batter pandan", "Masak crepe yang nipis", "Isi dengan kelapa gula dan gulung"],
      en: ["Make pandan batter", "Cook thin crepe", "Fill with coconut sugar and roll"],
    },
  },
  {
    id: "r065",
    name: { bm: "Kuih Talam", en: "Talam Kuih" },
    ingredients: ["Tepung", "Santan", "Gula", "Daun Pandan", "Minyak Masak", "Garam"],
    prepTime: 90,
    estimatedCost: 5.0,
    calories: 220,
    tags: ["halal", "kuih", "tradisional", "Steamed"],
    steps: {
      bm: ["Buat lapisan bawah dari gula dan santan", "Buat lapisan atas dari santan", "Kukus sehingga masak"],
      en: ["Make bottom layer from sugar and coconut milk", "Make top layer from coconut milk", "Steam until cooked"],
    },
  },
  {
    id: "r066",
    name: { bm: "Bingka Ubi", en: "Tapioca Cake" },
    ingredients: ["Ubi Kayu", "Santan", "Gula", "Telur", "Minyak Masak", "Garam"],
    prepTime: 90,
    estimatedCost: 6.0,
    calories: 280,
    tags: ["halal", "kuih", "tradisional", "bakar"],
    steps: {
      bm: ["Parut ubi kayu", "Campurkan dengan santan dan gula", "Bakar sehingga masak"],
      en: ["Grate tapioca", "Mix with coconut milk and sugar", "Bake until cooked"],
    },
  },
  {
    id: "r067",
    name: { bm: "Kuih Bahulu", en: "Bahulu" },
    ingredients: ["Telur", "Gula", "Tepung", "Minyak Masak", "Garam"],
    prepTime: 40,
    estimatedCost: 4.0,
    calories: 180,
    tags: ["halal", "kuih", "tradisional", "bakar"],
    steps: {
      bm: ["Pukul telur dan gula", "Masukkan tepung", "Cetek dalam acuan ikan"],
      en: ["Beat egg and sugar", "Add flour", "Mold in fish-shaped mold"],
    },
  },
  {
    id: "r068",
    name: { bm: "Pulut Inti", en: "Glutinous Rice with Coconut" },
    ingredients: ["Beras", "Kelapa", "Gula", "Santan", "Garam"],
    prepTime: 70,
    estimatedCost: 4.0,
    calories: 260,
    tags: ["halal", "kuih", "tradisional", "pulut"],
    steps: {
      bm: ["Masak pulut dengan santan", "Buat inti kelapa gula", "Hidangkan bersama"],
      en: ["Cook glutinous rice with coconut milk", "Make coconut sugar filling", "Serve together"],
    },
  },
  {
    id: "r069",
    name: { bm: "Lepat Pisang", en: "Banana Glutinous Rice" },
    ingredients: ["Beras", "Pisang", "Kelapa", "Gula", "Santan", "Minyak Masak", "Garam"],
    prepTime: 80,
    estimatedCost: 5.0,
    calories: 300,
    tags: ["halal", "kuih", "tradisional", "bungkus"],
    steps: {
      bm: ["Bungkus pulut dan pisang dalam daun pisang", "Kukus selama 45 minit"],
      en: ["Wrap glutinous rice and banana in banana leaves", "Steam for 45 minutes"],
    },
  },
  {
    id: "r070",
    name: { bm: "Kuih Koci", en: "Koci Kuih" },
    ingredients: ["Tepung", "Santan", "Gula", "Kelapa", "Minyak Masak", "Garam"],
    prepTime: 75,
    estimatedCost: 5.0,
    calories: 250,
    tags: ["halal", "kuih", "tradisional", "Steamed"],
    steps: {
      bm: ["Buat doh dan isian", "Bentuk kuih dan kukus", "Gulungkan kelapa parut"],
      en: ["Make dough and filling", "Shape and steam", "Roll in grated coconut"],
    },
  },
  {
    id: "r071",
    name: { bm: "Putu Piring", en: "Putu Piring" },
    ingredients: ["Tepung", "Gula", "Kelapa", "Santan", "Minyak Masak", "Garam"],
    prepTime: 60,
    estimatedCost: 4.0,
    calories: 230,
    tags: ["halal", "kuih", "tradisional", "Steamed"],
    steps: {
      bm: ["Buat doh dan isian gula merah", "Kukus dalam acuan"],
      en: ["Make dough and palm sugar filling", "Steam in mold"],
    },
  },
  {
    id: "r072",
    name: { bm: "Kuih Pelita", en: "Lantern Kuih" },
    ingredients: ["Tepung", "Santan", "Gula", "Daun Pandan", "Minyak Masak", "Garam"],
    prepTime: 85,
    estimatedCost: 5.0,
    calories: 210,
    tags: ["halal", "kuih", "tradisional", "Steamed"],
    steps: {
      bm: ["Buat batter dan bancuh santan", "Kukus dalam acuan daun pisang"],
      en: ["Make batter and dilute coconut milk", "Steam in banana leaf molds"],
    },
  },
  // === BEVERAGES ===
  {
    id: "r073",
    name: { bm: "Teh Tarik", en: "Pulled Tea" },
    ingredients: ["Teh", "Gula", "Santan", "Air"],
    prepTime: 15,
    estimatedCost: 1.5,
    calories: 120,
    tags: ["halal", "minuman", "popular", "mamak"],
    steps: {
      bm: ["Bancuh teh dan gula", "Tarik-tegangkan untuk foam", "Hidangkan panas"],
      en: ["Mix tea and sugar", "Pull for foam", "Serve hot"],
    },
  },
  {
    id: "r074",
    name: { bm: "Milo Dinosaur", en: "Dinosaur Milo" },
    ingredients: ["Milo", "Gula", "Santan", "Air"],
    prepTime: 10,
    estimatedCost: 2.0,
    calories: 180,
    tags: ["halal", "minuman", "popular", " sejuk"],
    steps: {
      bm: ["Bancuh Milo pekat", "Tambah gula dan santan", "Kacau rata"],
      en: ["Mix thick Milo", "Add sugar and coconut milk", "Stir well"],
    },
  },
  {
    id: "r075",
    name: { bm: "Bandung", en: "Bandung Drink" },
    ingredients: ["Susu", "Gula", "Siram Bandung", "Air"],
    prepTime: 3,
    estimatedCost: 1.5,
    calories: 140,
    tags: ["halal", "minuman", "popular", "sejuk"],
    steps: {
      bm: ["Campurkan susu dan sirap", "Tambah gula", "Kacau danhidang sejuk"],
      en: ["Mix milk and syrup", "Add sugar", "Stir and serve cold"],
    },
  },
  {
    id: "r076",
    name: { bm: "Cendol", en: "Cendol" },
    ingredients: ["Tepung", "Santan", "Gula", "Daun Pandan", "Ais", "Merah"],
    prepTime: 50,
    estimatedCost: 3.0,
    calories: 160,
    tags: ["halal", "minuman", "dessert", "sejuk"],
    steps: {
      bm: ["Buat dough cendol", "Masak gula merah", "Sediakan santan pandan", "Campurkan semua dengan ais"],
      en: ["Make cendol dough", "Cook palm sugar", "Prepare pandan coconut milk", "Combine all with ice"],
    },
  },
  {
    id: "r077",
    name: { bm: "Air Kelapa", en: "Coconut Water" },
    ingredients: ["Kelapa", "Es Batu"],
    prepTime: 5,
    estimatedCost: 2.5,
    calories: 45,
    tags: ["halal", "minuman", "segar", "semulajadi"],
    steps: {
      bm: ["Buka kelapa", "Tuang air dan tambah ais"],
      en: ["Open coconut", "Pour water and add ice"],
    },
  },
  {
    id: "r078",
    name: { bm: "Jus Mangga", en: "Mango Juice" },
    ingredients: ["Mangga", "Gula", "Susu", "Es Batu"],
    prepTime: 10,
    estimatedCost: 4.0,
    calories: 150,
    tags: ["halal", "minuman", "buah", "sejuk"],
    steps: {
      bm: ["Kupas dan potong mangga", "Kisar dengan susu dan gula", "Tambah ais"],
      en: ["Peel and cut mango", "Blend with milk and sugar", "Add ice"],
    },
  },
  {
    id: "r079",
    name: { bm: "Ais Kosong", en: "Iced Water" },
    ingredients: ["Air", "Es Batu"],
    prepTime: 2,
    estimatedCost: 0.5,
    calories: 0,
    tags: ["halal", "minuman", "segar", "murah"],
    steps: {
      bm: ["Isi gelas dengan ais", "Tuang air"],
      en: ["Fill glass with ice", "Pour water"],
    },
  },
  // === SALADS AND SIDES ===
  {
    id: "r080",
    name: { bm: "Rojak Buah", en: "Fruit Rojak" },
    ingredients: ["Timun", "Nanas", "Mangga", "Bengkoang", "Kicap", "Gula", "Cili", "Kacang", "Garam"],
    prepTime: 20,
    estimatedCost: 6.0,
    calories: 200,
    tags: ["halal", "salad", "manis", "pedas"],
    steps: {
      bm: ["Potong semua buah", "Gaul dengan kuah rojak"],
      en: ["Cut all fruits", "Mix with rojak sauce"],
    },
  },
  {
    id: "r081",
    name: { bm: "Rojak Mamak", en: "Mamak Rojak" },
    ingredients: ["Tahu", "Telur", "Sosej", "Kentang", "Bawang Merah", "Kicap", "Gula", "Kacang", "Cili", "Minyak Masak", "Garam"],
    prepTime: 55,
    estimatedCost: 8.0,
    calories: 320,
    tags: ["halal", "salad", "mamak", "goreng"],
    steps: {
      bm: ["Goreng semua bahan", "Potong dan campurkan", "Siram dengan kuah rojak"],
      en: ["Fry all ingredients", "Cut and combine", "Pour rojak sauce over"],
    },
  },
  {
    id: "r082",
    name: { bm: "Acar Timun", en: "Cucumber Pickle" },
    ingredients: ["Timun", "Bawang Merah", "Cili", "Cuka", "Gula", "Garam"],
    prepTime: 15,
    estimatedCost: 2.0,
    calories: 60,
    tags: ["halal", "acar", "segar", "pedas"],
    steps: {
      bm: ["Potong timun dan bawang", "Campurkan dengan cuka, gula dan cili", "Rehatkan sebelumhidang"],
      en: ["Cut cucumber and onion", "Mix with vinegar, sugar and chili", "Rest before serving"],
    },
  },
  {
    id: "r083",
    name: { bm: "Gado-Gado", en: "Gado-Gado Salad" },
    ingredients: ["Tahu", "Telur", "Kentang", "Tauge", "Sayur Sawi", "Kicap", "Gula", "Kacang", "Cili", "Minyak Masak", "Garam"],
    prepTime: 65,
    estimatedCost: 8.0,
    calories: 280,
    tags: ["halal", "salad", "Indonesian", "lemak"],
    steps: {
      bm: ["Rebus dan goreng semua bahan", "Susun dalam pinggan", "Siram dengan kuah kacang"],
      en: ["Boil and fry all ingredients", "Arrange on plate", "Pour peanut sauce over"],
    },
  },
  // === MORE SIMPLE RECIPES FOR TESTING ===
  {
    id: "r084",
    name: { bm: "Sambal Belacan Ringkas", en: "Simple Shrimp Paste Sambal" },
    ingredients: ["Cili", "Belacan", "Limau", "Gula", "Garam"],
    prepTime: 15,
    estimatedCost: 2.0,
    calories: 50,
    tags: ["halal", "sambal", "pedas", "cepat"],
    steps: {
      bm: ["Kisar cili dan belacan", "Perah limau dan tambah gula", "Kacau rata"],
      en: ["Blend chili and shrimp paste", "Squeeze lime and add sugar", "Mix well"],
    },
  },
  {
    id: "r085",
    name: { bm: "Kicap Halia", en: "Ginger Soy Sauce" },
    ingredients: ["Kicap", "Halia", "Gula", "Minyak Masak"],
    prepTime: 10,
    estimatedCost: 1.0,
    calories: 40,
    tags: ["halal", "sos", "cepat", "cina"],
    steps: {
      bm: ["Reneh kicap dengan halia", "Tambah gula", "Sejukkan sebelumhidang"],
      en: ["Simmer soy sauce with ginger", "Add sugar", "Cool before serving"],
    },
  },
  {
    id: "r086",
    name: { bm: "Telur Hampa", en: "Egg Omelette" },
    ingredients: ["Telur", "Minyak Masak", "Kicap"],
    prepTime: 13,
    estimatedCost: 0.8,
    calories: 180,
    tags: ["halal", "telur", "cepat", "sarapan"],
    steps: {
      bm: ["Pukul telur", "Goreng nipis seperti crepe", "Lipat danhidang dengan kicap"],
      en: ["Beat eggs", "Fry thin like a crepe", "Fold and serve with soy sauce"],
    },
  },
  {
    id: "r087",
    name: { bm: "Nasi Dagang Ringkas", en: "Simple Trader's Rice" },
    ingredients: ["Beras", "Santan", "Garam", "Halia"],
    prepTime: 40,
    estimatedCost: 3.0,
    calories: 350,
    tags: ["halal", "nasi", "cepat", "dasar"],
    steps: {
      bm: ["Masak beras dengan santan", "Tambah halia dan garam"],
      en: ["Cook rice with coconut milk", "Add ginger and salt"],
    },
  },
  {
    id: "r088",
    name: { bm: "Bubur Cha Cha", en: "Sweet Coconut Dessert" },
    ingredients: ["Ubi Kayu", "Kelapa", "Gula", "Santan", "Daun Pandan", "Garam"],
    prepTime: 60,
    estimatedCost: 5.0,
    calories: 250,
    tags: ["halal", "dessert", "tradisional", "manis"],
    steps: {
      bm: ["Potong ubi dan masak dengan gula", "Masak santan pandan", "Campurkan danhidang"],
      en: ["Cut yam and cook with sugar", "Cook pandan coconut milk", "Combine and serve"],
    },
  },
  {
    id: "r089",
    name: { bm: "Ais Kachang", en: "Ice Kachang" },
    ingredients: ["Es Batu", "Kacang Merah", "Jeli", "Santan", "Gula Merah", "Cincau"],
    prepTime: 35,
    estimatedCost: 4.0,
    calories: 180,
    tags: ["halal", "dessert", "sejuk", "popular"],
    steps: {
      bm: ["Kisar ais", "Sediakan topping", "Susun dalam mangkuk"],
      en: ["Blend ice", "Prepare toppings", "Arrange in bowl"],
    },
  },
  {
    id: "r090",
    name: { bm: "Sago Pudding", en: "Sago Pudding" },
    ingredients: ["Sagu", "Santan", "Gula", "Daun Pandan", "Garam"],
    prepTime: 45,
    estimatedCost: 4.0,
    calories: 200,
    tags: ["halal", "dessert", "tradisional", "Steamed"],
    steps: {
      bm: ["Masak sagu sehingga lutsinar", "Masak santan pandan", "Campurkan dan sejukkan"],
      en: ["Cook sago until translucent", "Cook pandan coconut milk", "Combine and cool"],
    },
  },
  {
    id: "r091",
    name: { bm: "Mee Hoon Goreng", en: "Fried Vermicelli" },
    ingredients: ["Mie", "Telur", "Bawang Merah", "Kicap", "Minyak Masak", "Gula", "Garam"],
    prepTime: 30,
    estimatedCost: 4.0,
    calories: 380,
    tags: ["halal", "mie", "cepat", "goreng"],
    steps: {
      bm: ["Rendam mee hoon", "Goreng telur dan ketepikan", "Tumis bawang dan mee", "Campurkan semua"],
      en: ["Soak vermicelli", "Fry egg and set aside", "Saute onion and noodles", "Combine all"],
    },
  },
  {
    id: "r092",
    name: { bm: "Sup Tulang", en: "Bone Soup" },
    ingredients: ["Tulang", "Bawang Putih", "Halia", "Serai", "Timun", "Garam"],
    prepTime: 140,
    estimatedCost: 10.0,
    calories: 200,
    tags: ["halal", "sup", "berkhasiat", "hangat"],
    steps: {
      bm: ["Rebus tulang selama 2 jam", "Masukkan rempah", "Perasa danhidang"],
      en: ["Boil bones for 2 hours", "Add spices", "Season and serve"],
    },
  },
  {
    id: "r093",
    name: { bm: "Ayam Perap Kicap", en: "Soy Sauce Marinated Chicken" },
    ingredients: ["Ayam", "Kicap", "Bawang Putih", "Gula", "Minyak Masak"],
    prepTime: 50,
    estimatedCost: 10.0,
    calories: 350,
    tags: ["halal", "ayam", "cepat", "cina"],
    steps: {
      bm: ["Perap ayam dengan kicap", "Grill atau panggan", "Hidangkan"],
      en: ["Marinate chicken with soy sauce", "Grill or bake", "Serve"],
    },
  },
  {
    id: "r094",
    name: { bm: "Bihun Sup", en: "Rice Noodle Soup" },
    ingredients: ["Beras", "Bawang Putih", "Halia", "Telur", "Sayur Sawi", "Garam"],
    prepTime: 40,
    estimatedCost: 4.0,
    calories: 220,
    tags: ["halal", "sup", "mie", "ringkas"],
    steps: {
      bm: ["Masak kuah dengan bawang dan halia", "Masak bihun berasingan", "Campurkan danhidang"],
      en: ["Cook broth with garlic and ginger", "Cook noodles separately", "Combine and serve"],
    },
  },
  {
    id: "r095",
    name: { bm: "Nasi Goreng Tom Yam", en: "Tom Yum Fried Rice" },
    ingredients: ["Beras", "Telur", "Tomato", "Cili", "Bawang Merah", "Kicap", "Minyak Masak", "Halia", "Gula", "Garam"],
    prepTime: 45,
    estimatedCost: 5.0,
    calories: 440,
    tags: ["halal", "nasi", "pedas", "Thai"],
    steps: {
      bm: ["Masak nasi", "Tumis tomato dan cili", "Masukkan nasi dan telur", "Perasa"],
      en: ["Cook rice", "Stir-fry tomato and chili", "Add rice and egg", "Season"],
    },
  },
  {
    id: "r096",
    name: { bm: "Tomyam Seafood", en: "Tom Yum Seafood" },
    ingredients: ["Udang", "Sotong", "Tomato", "Cili", "Halia", "Serai", "Limau", "Minyak Masak", "Gula", "Garam"],
    prepTime: 45,
    estimatedCost: 16.0,
    calories: 250,
    tags: ["halal", "sup", "pedas", "Thai"],
    steps: {
      bm: ["Masak air dengan rempah", "Masukkan seafood dan tomato", "Perasa dengan gula dan limau"],
      en: ["Boil water with spices", "Add seafood and tomato", "Season with sugar and lime"],
    },
  },
  {
    id: "r097",
    name: { bm: "Pais Ikan", en: "Banana Leaf Fish" },
    ingredients: ["Ikan", "Cili", "Bawang Merah", "Bawang Putih", "Tomato", "Serai", "Minyak Masak", "Gula", "Garam"],
    prepTime: 75,
    estimatedCost: 14.0,
    calories: 300,
    tags: ["halal", "ikan", "panggang", "Nyonya"],
    steps: {
      bm: ["Perap ikan dengan rempah", "Bungkus dengan daun pisang", "Panggang selama 45 minit"],
      en: ["Marinate fish with spices", "Wrap in banana leaves", "Bake for 45 minutes"],
    },
  },
  {
    id: "r098",
    name: { bm: "Masak Tempoyak", en: "Tempoyak Curry" },
    ingredients: ["Ikan", "Tempoyak", "Cili", "Bawang Merah", "Serai", "Halia", "Minyak Masak", "Gula", "Garam"],
    prepTime: 60,
    estimatedCost: 12.0,
    calories: 280,
    tags: ["halal", "lauk", "ikan", "Pedagang"],
    steps: {
      bm: ["Masak tempoyak dengan rempah", "Masukkan ikan", "Masak sehingga masak"],
      en: ["Cook tempoyak with spices", "Add fish", "Cook until done"],
    },
  },
  {
    id: "r099",
    name: { bm: "Kerabu Maggi", en: "Maggi Salad" },
    ingredients: ["Mie", "Timun", "Tomato", "Bawang Merah", "Cili", "Kicap", "Gula", "Limau", "Minyak Masak"],
    prepTime: 25,
    estimatedCost: 3.0,
    calories: 260,
    tags: ["halal", "salad", "cepat", "ringkas"],
    steps: {
      bm: ["Rebus maggi dan sejukkan", "Potong sayur", "Campurkan dengan kuah"],
      en: ["Boil noodles and cool", "Cut vegetables", "Mix with sauce"],
    },
  },
  {
    id: "r100",
    name: { bm: "Pisang Goreng", en: "Fried Banana" },
    ingredients: ["Pisang", "Tepung", "Gula", "Minyak Masak", "Garam"],
    prepTime: 30,
    estimatedCost: 2.5,
    calories: 240,
    tags: ["halal", "snack", "goreng", "popular"],
    steps: {
      bm: ["Potong pisang", "Gaul dengan batter tepung", "Goreng sehingga keemasan"],
      en: ["Cut banana", "Mix with flour batter", "Fry until golden"],
    },
  },
  {
    id: "r101",
    name: { bm: "Kuih Kosang", en: "Sweet Potato Balls" },
    ingredients: ["Ubi Kayu", "Tepung", "Gula", "Kelapa", "Minyak Masak", "Garam"],
    prepTime: 50,
    estimatedCost: 4.0,
    calories: 220,
    tags: ["halal", "kuih", "goreng", "tradisional"],
    steps: {
      bm: ["Kukus dan lenyek ubi", "Bentuk bulat dengan inti gula", "Goreng"],
      en: ["Steam and mash yam", "Shape balls with sugar filling", "Fry"],
    },
  },
  {
    id: "r102",
    name: { bm: "Cucur Badak", en: "Cucur Badak" },
    ingredients: ["Ubi Kayu", "Tepung", "Gula", "Kelapa", "Minyak Masak", "Garam"],
    prepTime: 40,
    estimatedCost: 3.5,
    calories: 200,
    tags: ["halal", "kuih", "goreng", "Melayu"],
    steps: {
      bm: ["Parut ubi dan campur tepung", "Bentuk dan goreng", "Gulungkan kelapa"],
      en: ["Grate yam and mix with flour", "Shape and fry", "Roll in coconut"],
    },
  },
  {
    id: "r103",
    name: { bm: "Mekdi", en: "Fried Shrimp Pancake" },
    ingredients: ["Udang", "Tepung", "Telur", "Bawang Merah", "Minyak Masak", "Gula", "Garam"],
    prepTime: 35,
    estimatedCost: 6.0,
    calories: 280,
    tags: ["halal", "snack", "goreng", "cina"],
    steps: {
      bm: ["Gaul udang dengan batter", "Goreng sehingga masak"],
      en: ["Mix shrimp with batter", "Fry until cooked"],
    },
  },
  {
    id: "r104",
    name: { bm: "Kuih Bangkit", en: "Kuih Bangkit" },
    ingredients: ["Tepung", "Kelapa", "Gula", "Minyak Masak", "Garam"],
    prepTime: 60,
    estimatedCost: 4.0,
    calories: 180,
    tags: ["halal", "kuih", "Hari Raya", "tradisional"],
    steps: {
      bm: ["Buat doh dan cetak", "Panggang sehingga garing"],
      en: ["Make dough and mold", "Bake until crispy"],
    },
  },
  {
    id: "r105",
    name: { bm: "Roti Jala", en: "Net Crepes" },
    ingredients: ["Tepung", "Telur", "Santan", "Kunyit", "Minyak Masak", "Garam"],
    prepTime: 45,
    estimatedCost: 3.0,
    calories: 200,
    tags: ["halal", "kuih", "Melayu", "tradisional"],
    steps: {
      bm: ["Buat batter dan tuang dalam acuan roti jala", "Masak sehingga masak"],
      en: ["Make batter and pour in roti jala mold", "Cook until done"],
    },
  },
  // === 2-INGREDIENT RECIPES FOR COMMON PANTRY ITEMS ===
  {
    id: "r106",
    name: { bm: "Telur Rebus (Air Sahaja)", en: "Boiled Egg (Water Only)" },
    ingredients: ["Telur", "Air"],
    prepTime: 12,
    estimatedCost: 0.4,
    calories: 140,
    tags: ["halal", "vegetarian", "cepat", "sarapan", "ringkas"],
    steps: {
      bm: ["Masukkan telur dalam air mendidih", "Rebus 10 minit", "Kupas dan hidang"],
      en: ["Add eggs to boiling water", "Boil for 10 minutes", "Peel and serve"],
    },
  },
  {
    id: "r107",
    name: { bm: "Telur Goreng (Minyak Sahaja)", en: "Fried Egg (Oil Only)" },
    ingredients: ["Telur", "Minyak Masak"],
    prepTime: 7,
    estimatedCost: 0.35,
    calories: 165,
    tags: ["halal", "vegetarian", "cepat", "sarapan", "ringkas"],
    steps: {
      bm: ["Panaskan minyak dalam kuali", "Pecahkan telur", "Goreng sehingga masak"],
      en: ["Heat oil in pan", "Crack egg", "Fry until cooked"],
    },
  },
  {
    id: "r108",
    name: { bm: "Telur Masak Tomat", en: "Eggs with Tomato" },
    ingredients: ["Telur", "Tomato"],
    prepTime: 15,
    estimatedCost: 0.8,
    calories: 130,
    tags: ["halal", "vegetarian", "cepat", "sarapan", "ringkas"],
    steps: {
      bm: ["Potong tomato", "Goreng telur dan tomato bersama"],
      en: ["Cut tomato", "Fry egg and tomato together"],
    },
  },
  {
    id: "r109",
    name: { bm: "Telur Masak Garam", en: "Salt Egg" },
    ingredients: ["Telur", "Garam"],
    prepTime: 15,
    estimatedCost: 0.3,
    calories: 140,
    tags: ["halal", "vegetarian", "cepat", "ringkas"],
    steps: {
      bm: ["Rebus telur dengan garam", "Kupas dan makan"],
      en: ["Boil egg with salt", "Peel and eat"],
    },
  },
  {
    id: "r110",
    name: { bm: "Nasi Goreng Kicap", en: "Soy Sauce Fried Rice" },
    ingredients: ["Nasi", "Kicap"],
    prepTime: 10,
    estimatedCost: 1.0,
    calories: 280,
    tags: ["halal", "vegetarian", "cepat", "makan tengahari", "ringkas"],
    steps: {
      bm: ["Panaskan minyak dan kicap", "Masukkan nasi sejuk", "Kacau sehingga rata"],
      en: ["Heat oil and soy sauce", "Add cold rice", "Stir until mixed"],
    },
  },
  {
    id: "r111",
    name: { bm: "Nasi Goreng Bawang Putih", en: "Garlic Fried Rice" },
    ingredients: ["Nasi", "Bawang Putih"],
    prepTime: 12,
    estimatedCost: 1.2,
    calories: 270,
    tags: ["halal", "vegetarian", "cepat", "cina", "ringkas"],
    steps: {
      bm: ["Tumis bawang putih", "Masukkan nasi", "Kacau rata"],
      en: ["Saute garlic", "Add rice", "Stir well"],
    },
  },
  {
    id: "r112",
    name: { bm: "Nasi Tom Yum", en: "Tom Yum Rice" },
    ingredients: ["Nasi", "Cili"],
    prepTime: 10,
    estimatedCost: 1.0,
    calories: 260,
    tags: ["halal", "vegetarian", "pedas", "ringkas"],
    steps: {
      bm: ["Tumis cili dengan minyak", "Campurkan dengan nasi"],
      en: ["Stir-fry chili with oil", "Mix with rice"],
    },
  },
  {
    id: "r113",
    name: { bm: "Mee Goreng Kicap", en: "Soy Sauce Fried Noodles" },
    ingredients: ["Mee", "Kicap"],
    prepTime: 10,
    estimatedCost: 1.5,
    calories: 320,
    tags: ["halal", "vegetarian", "cepat", "makan tengahari", "ringkas"],
    steps: {
      bm: ["Rebus mee dan toskan", "Goreng dengan kicap"],
      en: ["Boil noodles and drain", "Fry with soy sauce"],
    },
  },
  {
    id: "r114",
    name: { bm: "Mee Goreng Bawang", en: "Garlic Fried Noodles" },
    ingredients: ["Mee", "Bawang Putih"],
    prepTime: 12,
    estimatedCost: 1.5,
    calories: 310,
    tags: ["halal", "vegetarian", "cepat", "cina", "ringkas"],
    steps: {
      bm: ["Rebus mee dan toskan", "Tumis bawang putih dan campurkan"],
      en: ["Boil noodles and drain", "Saute garlic and mix"],
    },
  },
  {
    id: "r115",
    name: { bm: "Roti Goreng Mentega", en: "Butter Fried Bread" },
    ingredients: ["Roti", "Mentega"],
    prepTime: 5,
    estimatedCost: 0.5,
    calories: 200,
    tags: ["halal", "vegetarian", "cepat", "sarapan", "ringkas"],
    steps: {
      bm: ["Panaskan mentega dalam kuali", "Goreng roti sehingga keemasan"],
      en: ["Heat butter in pan", "Fry bread until golden"],
    },
  },
  {
    id: "r116",
    name: { bm: "Roti Kicap", en: "Soy Sauce Toast" },
    ingredients: ["Roti", "Kicap"],
    prepTime: 3,
    estimatedCost: 0.3,
    calories: 180,
    tags: ["halal", "vegetarian", "cepat", "sarapan", "ringkas"],
    steps: {
      bm: ["Panaskan roti", "Siram kicap di atas"],
      en: ["Toast bread", "Drizzle soy sauce on top"],
    },
  },
  {
    id: "r117",
    name: { bm: "Roti Gulung Gula", en: "Sugar Roll Bread" },
    ingredients: ["Roti", "Gula"],
    prepTime: 5,
    estimatedCost: 0.4,
    calories: 190,
    tags: ["halal", "vegetarian", "cepat", "sarapan", "manis", "ringkas"],
    steps: {
      bm: ["Ratakan roti", "Tabur gula dan gulung"],
      en: ["Flatten bread", "Sprinkle sugar and roll"],
    },
  },
  {
    id: "r118",
    name: { bm: "Ais Gula", en: "Sweet Ice Water" },
    ingredients: ["Air", "Gula"],
    prepTime: 2,
    estimatedCost: 0.2,
    calories: 80,
    tags: ["halal", "vegetarian", "minuman", "sejuk", "murah", "ringkas"],
    steps: {
      bm: ["Campurkan air dengan gula", "Kacau sehingga larut"],
      en: ["Mix water with sugar", "Stir until dissolved"],
    },
  },
  {
    id: "r119",
    name: { bm: "Teh Tarik Simple", en: "Simple Pulled Tea" },
    ingredients: ["Teh", "Susu"],
    prepTime: 8,
    estimatedCost: 1.0,
    calories: 100,
    tags: ["halal", "minuman", "popular", "ringkas"],
    steps: {
      bm: ["Bancuh teh pekat", "Tambah susu dan kacau", "Tarik untuk foam"],
      en: ["Brew strong tea", "Add milk and stir", "Pull for foam"],
    },
  },
  {
    id: "r120",
    name: { bm: "Teh Manis", en: "Sweet Tea" },
    ingredients: ["Teh", "Gula"],
    prepTime: 5,
    estimatedCost: 0.5,
    calories: 90,
    tags: ["halal", "minuman", "popular", "murah", "ringkas"],
    steps: {
      bm: ["Bancuh teh", "Tambah gula dan kacau"],
      en: ["Brew tea", "Add sugar and stir"],
    },
  },
  {
    id: "r121",
    name: { bm: "Limau Teh", en: "Lime Tea" },
    ingredients: ["Teh", "Limau nipis"],
    prepTime: 5,
    estimatedCost: 1.0,
    calories: 50,
    tags: ["halal", "minuman", "segar", "ringkas"],
    steps: {
      bm: ["Bancuh teh", "Perah limau nipis dan campurkan"],
      en: ["Brew tea", "Squeeze lime and mix"],
    },
  },
  {
    id: "r122",
    name: { bm: "Susu Gula", en: "Sweet Milk" },
    ingredients: ["Susu", "Gula"],
    prepTime: 2,
    estimatedCost: 0.8,
    calories: 150,
    tags: ["halal", "minuman", "kanak-kanak", "murah", "ringkas"],
    steps: {
      bm: ["Panaskan susu", "Tambah gula dan kacau"],
      en: ["Warm milk", "Add sugar and stir"],
    },
  },
  {
    id: "r123",
    name: { bm: "Limau Ais", en: "Iced Lime Drink" },
    ingredients: ["Air", "Limau nipis"],
    prepTime: 2,
    estimatedCost: 0.5,
    calories: 25,
    tags: ["halal", "vegetarian", "minuman", "segar", "murah", "ringkas"],
    steps: {
      bm: ["Perah limau nipis ke dalam air", "Kacau danhidang sejuk"],
      en: ["Squeeze lime into water", "Stir and serve cold"],
    },
  },
  {
    id: "r124",
    name: { bm: "Gula Air Hangat", en: "Warm Sugar Water" },
    ingredients: ["Air", "Gula"],
    prepTime: 3,
    estimatedCost: 0.2,
    calories: 80,
    tags: ["halal", "vegetarian", "minuman", "hangat", "murah", "ringkas"],
    steps: {
      bm: ["Panaskan air", "Masukkan gula dan kacau"],
      en: ["Heat water", "Add sugar and stir"],
    },
  },
  {
    id: "r125",
    name: { bm: "Timun Kicap", en: "Cucumber Soy Sauce" },
    ingredients: ["Timun", "Kicap"],
    prepTime: 5,
    estimatedCost: 0.5,
    calories: 35,
    tags: ["halal", "vegetarian", "cepat", "ringkas"],
    steps: {
      bm: ["Potong timun", "Siram kicap di atas"],
      en: ["Slice cucumber", "Drizzle soy sauce on top"],
    },
  },
  {
    id: "r126",
    name: { bm: "Timun Garam", en: "Salt Cucumber" },
    ingredients: ["Timun", "Garam"],
    prepTime: 3,
    estimatedCost: 0.3,
    calories: 20,
    tags: ["halal", "vegetarian", "cepat", "ringkas"],
    steps: {
      bm: ["Potong timun", "Tabur garam dan makan"],
      en: ["Slice cucumber", "Sprinkle salt and eat"],
    },
  },
  {
    id: "r127",
    name: { bm: "Tomato Garam", en: "Salt Tomato" },
    ingredients: ["Tomato", "Garam"],
    prepTime: 3,
    estimatedCost: 0.4,
    calories: 25,
    tags: ["halal", "vegetarian", "cepat", "ringkas"],
    steps: {
      bm: ["Potong tomato", "Tabur garam"],
      en: ["Cut tomato", "Sprinkle salt"],
    },
  },
  {
    id: "r128",
    name: { bm: "Bawang Goreng", en: "Fried Shallots" },
    ingredients: ["Bawang Merah", "Minyak Masak"],
    prepTime: 10,
    estimatedCost: 1.0,
    calories: 90,
    tags: ["halal", "vegetarian", "ringkas", "garnish"],
    steps: {
      bm: ["Potong bawang merah nipis", "Goreng dalam minyak sehingga keemasan"],
      en: ["Slice shallots thinly", "Fry in oil until golden"],
    },
  },
  {
    id: "r129",
    name: { bm: "Cili Garam", en: "Salt Chili" },
    ingredients: ["Cili", "Garam"],
    prepTime: 2,
    estimatedCost: 0.3,
    calories: 20,
    tags: ["halal", "vegetarian", "pedas", "ringkas"],
    steps: {
      bm: ["Potong cili", "Tabur garam"],
      en: ["Cut chili", "Sprinkle salt"],
    },
  },
  {
    id: "r130",
    name: { bm: "Halia Kicap", en: "Ginger Soy Sauce" },
    ingredients: ["Halia", "Kicap"],
    prepTime: 3,
    estimatedCost: 0.5,
    calories: 30,
    tags: ["halal", "vegetarian", "ringkas", "cina"],
    steps: {
      bm: ["Potong halia nipis", "Celup dalam kicap"],
      en: ["Slice ginger thinly", "Dip in soy sauce"],
    },
  },
];

export const communityRecipesSeed: CommunityRecipe[] = [
  {
    id: "c1",
    title: { bm: "Sambal Telur Paling Jimat", en: "Budget Egg Sambal" },
    author: "Puan Siti",
    rating: 4.5,
    comments: 12,
  },
  {
    id: "c2",
    title: { bm: "Mi Goreng Ala Mamak", en: "Mamak Style Fried Noodles" },
    author: "Hafiz_KL",
    rating: 4.8,
    comments: 28,
  },
  {
    id: "c3",
    title: { bm: "Sup Tulang Mudah", en: "Easy Bone Soup" },
    author: "Kak Anis",
    rating: 4.2,
    comments: 7,
  },
  {
    id: "c4",
    title: { bm: "Nasi Lemak Viral", en: "Viral Nasi Lemak" },
    author: "Chef Mel",
    rating: 4.9,
    comments: 45,
  },
  {
    id: "c5",
    title: { bm: "Rendang Ayah Sepanjang Jalan", en: "Dad's Long Cooked Rendang" },
    author: "Ahmad_Renda",
    rating: 5.0,
    comments: 32,
  },
];
